import type { Exercise, MovementPattern, WorkoutType } from "./types";

function ex(
  name: string,
  category: WorkoutType,
  pattern: MovementPattern | null = null
): Exercise {
  return {
    id: name.toLowerCase().replace(/[\s/]+/g, "-"),
    name,
    category,
    movementPattern: pattern,
    isCustom: false,
  };
}

export const builtInExercises: Exercise[] = [
  // ── Squat ──
  ex("Back Squat", "strength", "squat"),
  ex("Front Squat", "strength", "squat"),
  ex("Goblet Squat", "strength", "squat"),
  ex("Leg Press", "strength", "squat"),
  ex("Hack Squat", "strength", "squat"),
  ex("Smith Machine Squat", "strength", "squat"),
  ex("Box Squat", "strength", "squat"),
  ex("Sissy Squat", "strength", "squat"),
  ex("Leg Extension", "strength", "squat"),
  ex("Wall Sit", "strength", "squat"),

  // ── Hinge ──
  ex("Deadlift", "strength", "hinge"),
  ex("Sumo Deadlift", "strength", "hinge"),
  ex("RDL", "strength", "hinge"),
  ex("Single Leg RDL", "strength", "hinge"),
  ex("Hip Thrust", "strength", "hinge"),
  ex("Barbell Hip Thrust", "strength", "hinge"),
  ex("Glute Bridge", "strength", "hinge"),
  ex("Single Leg Glute Bridge", "strength", "hinge"),
  ex("Good Morning", "strength", "hinge"),
  ex("Cable Pull-Through", "strength", "hinge"),
  ex("Kettlebell Swing", "strength", "hinge"),
  ex("Leg Curl", "strength", "hinge"),
  ex("Seated Leg Curl", "strength", "hinge"),
  ex("Nordic Curl", "strength", "hinge"),
  ex("Back Extension", "strength", "hinge"),
  ex("Glute Kickback", "strength", "hinge"),
  ex("Cable Glute Kickback", "strength", "hinge"),

  // ── Lunge ──
  ex("Walking Lunge", "strength", "lunge"),
  ex("Reverse Lunge", "strength", "lunge"),
  ex("Bulgarian Split Squat", "strength", "lunge"),
  ex("Step-Up", "strength", "lunge"),
  ex("Lateral Lunge", "strength", "lunge"),
  ex("Curtsy Lunge", "strength", "lunge"),
  ex("Split Squat", "strength", "lunge"),
  ex("Deficit Lunge", "strength", "lunge"),

  // ── Push ──
  ex("Bench Press", "strength", "push"),
  ex("Incline Bench Press", "strength", "push"),
  ex("Decline Bench Press", "strength", "push"),
  ex("Dumbbell Bench Press", "strength", "push"),
  ex("Incline Dumbbell Press", "strength", "push"),
  ex("OHP", "strength", "push"),
  ex("Dumbbell Shoulder Press", "strength", "push"),
  ex("Arnold Press", "strength", "push"),
  ex("Push-Up", "strength", "push"),
  ex("Diamond Push-Up", "strength", "push"),
  ex("Pike Push-Up", "strength", "push"),
  ex("Dips", "strength", "push"),
  ex("Cable Chest Fly", "strength", "push"),
  ex("Dumbbell Fly", "strength", "push"),
  ex("Incline Fly", "strength", "push"),
  ex("Lateral Raise", "strength", "push"),
  ex("Front Raise", "strength", "push"),
  ex("Cable Lateral Raise", "strength", "push"),
  ex("Tricep Pushdown", "strength", "push"),
  ex("Overhead Tricep Extension", "strength", "push"),
  ex("Skull Crusher", "strength", "push"),
  ex("Close Grip Bench Press", "strength", "push"),
  ex("Tricep Kickback", "strength", "push"),

  // ── Pull ──
  ex("Barbell Row", "strength", "pull"),
  ex("Pendlay Row", "strength", "pull"),
  ex("Dumbbell Row", "strength", "pull"),
  ex("Cable Row", "strength", "pull"),
  ex("Seated Cable Row", "strength", "pull"),
  ex("T-Bar Row", "strength", "pull"),
  ex("Lat Pulldown", "strength", "pull"),
  ex("Wide Grip Lat Pulldown", "strength", "pull"),
  ex("Close Grip Lat Pulldown", "strength", "pull"),
  ex("Pull-Up", "strength", "pull"),
  ex("Chin-Up", "strength", "pull"),
  ex("Neutral Grip Pull-Up", "strength", "pull"),
  ex("Face Pull", "strength", "pull"),
  ex("Rear Delt Fly", "strength", "pull"),
  ex("Cable Rear Delt Fly", "strength", "pull"),
  ex("Shrug", "strength", "pull"),
  ex("Dumbbell Shrug", "strength", "pull"),
  ex("Barbell Curl", "strength", "pull"),
  ex("Dumbbell Curl", "strength", "pull"),
  ex("Hammer Curl", "strength", "pull"),
  ex("Incline Dumbbell Curl", "strength", "pull"),
  ex("Cable Curl", "strength", "pull"),
  ex("Preacher Curl", "strength", "pull"),
  ex("Concentration Curl", "strength", "pull"),

  // ── Core ──
  ex("Plank", "strength", "core"),
  ex("Side Plank", "strength", "core"),
  ex("Dead Bug", "strength", "core"),
  ex("Pallof Press", "strength", "core"),
  ex("Farmer's Carry", "strength", "core"),
  ex("Suitcase Carry", "strength", "core"),
  ex("Ab Rollout", "strength", "core"),
  ex("Hanging Leg Raise", "strength", "core"),
  ex("Cable Crunch", "strength", "core"),
  ex("Woodchop", "strength", "core"),
  ex("Russian Twist", "strength", "core"),
  ex("Mountain Climbers", "strength", "core"),
  ex("Bird Dog", "strength", "core"),
  ex("Bicycle Crunch", "strength", "core"),
  ex("V-Up", "strength", "core"),
  ex("Flutter Kicks", "strength", "core"),
  ex("Crunches", "strength", "core"),
  ex("Reverse Crunch", "strength", "core"),
  ex("Toe Touch", "strength", "core"),

  // ── Pilates ──
  ex("Hundred", "pilates"),
  ex("Roll-Up", "pilates"),
  ex("Single Leg Stretch", "pilates"),
  ex("Double Leg Stretch", "pilates"),
  ex("Teaser", "pilates"),
  ex("Pilates Plank", "pilates"),
  ex("Pilates Side Plank", "pilates"),
  ex("Bridge", "pilates"),
  ex("Swimming", "pilates"),
  ex("Leg Pull", "pilates"),
  ex("Scissors", "pilates"),
  ex("Corkscrew", "pilates"),
  ex("Saw", "pilates"),
  ex("Spine Stretch", "pilates"),
  ex("Mermaid", "pilates"),
  ex("Swan", "pilates"),
  ex("Seal", "pilates"),
  ex("Boomerang", "pilates"),
  ex("Side Kick Series", "pilates"),
  ex("Inner Thigh Lift", "pilates"),
  ex("Clam", "pilates"),
  ex("Roll Over", "pilates"),
  ex("Jackknife", "pilates"),
  ex("Open Leg Rocker", "pilates"),

  // ── Yoga ──
  ex("Sun Salutation A", "yoga"),
  ex("Sun Salutation B", "yoga"),
  ex("Warrior I", "yoga"),
  ex("Warrior II", "yoga"),
  ex("Warrior III", "yoga"),
  ex("Triangle", "yoga"),
  ex("Extended Side Angle", "yoga"),
  ex("Half Moon", "yoga"),
  ex("Pigeon", "yoga"),
  ex("Downward Dog", "yoga"),
  ex("Upward Dog", "yoga"),
  ex("Tree", "yoga"),
  ex("Chair", "yoga"),
  ex("Crow", "yoga"),
  ex("Eagle", "yoga"),
  ex("Dancer", "yoga"),
  ex("Bridge Pose", "yoga"),
  ex("Wheel", "yoga"),
  ex("Camel", "yoga"),
  ex("Cobra", "yoga"),
  ex("Locust", "yoga"),
  ex("Boat", "yoga"),
  ex("Seated Forward Fold", "yoga"),
  ex("Head to Knee", "yoga"),
  ex("Reclined Twist", "yoga"),
  ex("Happy Baby", "yoga"),
  ex("Legs Up the Wall", "yoga"),
  ex("Savasana", "yoga"),

  // ── Mobility / Stretches ──
  ex("Hip Flexor Stretch", "mobility"),
  ex("Pigeon Stretch", "mobility"),
  ex("Cat-Cow", "mobility"),
  ex("Thoracic Rotation", "mobility"),
  ex("90/90 Hip Switch", "mobility"),
  ex("Foam Roll Quads", "mobility"),
  ex("Foam Roll IT Band", "mobility"),
  ex("Foam Roll Glutes", "mobility"),
  ex("Foam Roll Upper Back", "mobility"),
  ex("Foam Roll Lats", "mobility"),
  ex("Foam Roll Calves", "mobility"),
  ex("Ankle Mobility", "mobility"),
  ex("Shoulder Dislocates", "mobility"),
  ex("World's Greatest Stretch", "mobility"),
  ex("Couch Stretch", "mobility"),
  ex("Frog Stretch", "mobility"),
  ex("Hamstring Stretch", "mobility"),
  ex("Quad Stretch", "mobility"),
  ex("Calf Stretch", "mobility"),
  ex("Chest Opener", "mobility"),
  ex("Lat Stretch", "mobility"),
  ex("Neck Stretch", "mobility"),
  ex("Child's Pose", "mobility"),
  ex("Thread the Needle", "mobility"),
  ex("Scorpion Stretch", "mobility"),
  ex("Banded Pull-Apart", "mobility"),
  ex("Banded Shoulder Stretch", "mobility"),
  ex("Lacrosse Ball Glutes", "mobility"),
  ex("Lacrosse Ball Pec", "mobility"),

  // ── Dumbbell home variations ──
  ex("Dumbbell Squat", "strength", "squat"),
  ex("Dumbbell Sumo Squat", "strength", "squat"),
  ex("Dumbbell RDL", "strength", "hinge"),
  ex("Dumbbell Single Leg RDL", "strength", "hinge"),
  ex("Dumbbell Hip Thrust", "strength", "hinge"),
  ex("Dumbbell Glute Bridge", "strength", "hinge"),
  ex("Dumbbell Lunge", "strength", "lunge"),
  ex("Dumbbell Reverse Lunge", "strength", "lunge"),
  ex("Dumbbell Bulgarian Split Squat", "strength", "lunge"),
  ex("Dumbbell Step-Up", "strength", "lunge"),
  ex("Dumbbell Lateral Lunge", "strength", "lunge"),
  ex("Dumbbell Floor Press", "strength", "push"),
  ex("Dumbbell Overhead Press", "strength", "push"),
  ex("Dumbbell Lateral Raise", "strength", "push"),
  ex("Dumbbell Front Raise", "strength", "push"),
  ex("Dumbbell Tricep Overhead Extension", "strength", "push"),
  ex("Dumbbell Kickback", "strength", "push"),
  ex("Dumbbell Bent Over Row", "strength", "pull"),
  ex("Dumbbell Reverse Fly", "strength", "pull"),
  ex("Dumbbell Curl", "strength", "pull"),
  ex("Dumbbell Hammer Curl", "strength", "pull"),
  ex("Dumbbell Concentration Curl", "strength", "pull"),
  ex("Dumbbell Pullover", "strength", "pull"),
  ex("Dumbbell Deadlift", "strength", "hinge"),
  ex("Dumbbell Calf Raise", "strength", "squat"),
  ex("Dumbbell Woodchop", "strength", "core"),
  ex("Dumbbell Russian Twist", "strength", "core"),
  ex("Dumbbell Plank Row", "strength", "core"),

  // ── Resistance band ──
  ex("Banded Squat", "strength", "squat"),
  ex("Banded Sumo Squat", "strength", "squat"),
  ex("Banded Deadlift", "strength", "hinge"),
  ex("Banded Hip Thrust", "strength", "hinge"),
  ex("Banded Glute Bridge", "strength", "hinge"),
  ex("Banded Glute Kickback", "strength", "hinge"),
  ex("Banded Lateral Walk", "strength", "squat"),
  ex("Banded Clamshell", "strength", "hinge"),
  ex("Banded Lunge", "strength", "lunge"),
  ex("Banded Shoulder Press", "strength", "push"),
  ex("Banded Push-Up", "strength", "push"),
  ex("Banded Lateral Raise", "strength", "push"),
  ex("Banded Tricep Pushdown", "strength", "push"),
  ex("Banded Row", "strength", "pull"),
  ex("Banded Face Pull", "strength", "pull"),
  ex("Banded Bicep Curl", "strength", "pull"),
  ex("Banded Good Morning", "strength", "hinge"),
  ex("Banded Pallof Press", "strength", "core"),
  ex("Banded Fire Hydrant", "strength", "hinge"),

  // ── Bodyweight ──
  ex("Jump Squat", "strength", "squat"),
  ex("Pistol Squat", "strength", "squat"),
  ex("Single Leg Glute Bridge", "strength", "hinge"),
  ex("Donkey Kick", "strength", "hinge"),
  ex("Fire Hydrant", "strength", "hinge"),
  ex("Inverted Row", "strength", "pull"),
  ex("Bodyweight Squat", "strength", "squat"),
  ex("Bodyweight Lunge", "strength", "lunge"),
  ex("Bodyweight Step-Up", "strength", "lunge"),
  ex("Bodyweight Calf Raise", "strength", "squat"),
  ex("Superman", "strength", "hinge"),
  ex("Glute March", "strength", "hinge"),
  ex("Bear Crawl", "strength", "core"),
  ex("Inchworm", "strength", "core"),
  ex("Burpee", "strength", "core"),
];
